
package paint;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineEvent.Type;
import javax.sound.sampled.LineListener;
import sound.SMClipPlayer;
import sound.SMPlayer;

public class VentanaInternaReproductor extends javax.swing.JInternalFrame {

    SMPlayer player;
    
    public VentanaInternaReproductor(File f) {
        initComponents();
        player = new SMClipPlayer(f);
        
        LineListener lineListener=new LineListener(){
            public void update(LineEvent event) {
                if(event.getType()==Type.START) { 
                    play.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/PlayDisabled_48x48.png")));
                    stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/StopNormalRed_48x48.png")));
                }
                if(event.getType()==Type.STOP) {
                    play.setSelected(false);
                    stop.setSelected(true);   
                    stop.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/StopDisabled_48x48.png")));
                }
            }
        };
        ((SMClipPlayer)player).setLineListener(lineListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoPlayStop = new javax.swing.ButtonGroup();
        play = new javax.swing.JToggleButton();
        stop = new javax.swing.JToggleButton();

        setClosable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        grupoPlayStop.add(play);
        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/PlayPressed_48x48.png"))); // NOI18N
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play);

        grupoPlayStop.add(stop);
        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/StopDisabled_48x48.png"))); // NOI18N
        stop.setSelected(true);
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        if(player!=null) player.play();
    }//GEN-LAST:event_playActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        if(player!=null) player.stop();
    }//GEN-LAST:event_stopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoPlayStop;
    private javax.swing.JToggleButton play;
    private javax.swing.JToggleButton stop;
    // End of variables declaration//GEN-END:variables
}
