
package paint;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sound.SMSoundRecorder;

public class VentanaInternaGrabador extends javax.swing.JInternalFrame {

    SMSoundRecorder recorder;
    
    public VentanaInternaGrabador(File f) {
        initComponents();
        recorder = new SMSoundRecorder(f);
        
        LineListener lineListener=new LineListener(){
            public void update(LineEvent event) {
                if(event.getType()==LineEvent.Type.START) { 
                    rec.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/RecordDisabled_48x48.png")));
                    stopRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/StopPessedBlue_48x48.png")));
                }
                if(event.getType()==LineEvent.Type.STOP) {
                    rec.setSelected(false);
                    stopRec.setSelected(true);   
                    stopRec.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/StopDisabled_48x48.png")));
                }
            }
        };
        recorder.setLineListener(lineListener);
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rec = new javax.swing.JToggleButton();
        stopRec = new javax.swing.JToggleButton();

        setClosable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        rec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/RecordPressed_48x48.png"))); // NOI18N
        rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recActionPerformed(evt);
            }
        });
        getContentPane().add(rec);

        stopRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sm/iconos/sonido/StopDisabled_48x48.png"))); // NOI18N
        stopRec.setSelected(true);
        stopRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopRecActionPerformed(evt);
            }
        });
        getContentPane().add(stopRec);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recActionPerformed
        if(recorder!=null) recorder.record();
    }//GEN-LAST:event_recActionPerformed

    private void stopRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopRecActionPerformed
        if(recorder!=null) recorder.stop();
    }//GEN-LAST:event_stopRecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton rec;
    private javax.swing.JToggleButton stopRec;
    // End of variables declaration//GEN-END:variables
}
